# Generated by Django 4.0.1 on 2022-02-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planercasa', '0002_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaApagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_produto', models.CharField(max_length=100)),
                ('data_do_pagamento', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
